-- MySQL Script generated by MySQL Workbench
-- Sat Apr 26 17:43:02 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Customer`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Customer` (
  `customer_id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(100) NOT NULL,
  `address` VARCHAR(200) NOT NULL,
  `phone_number` VARCHAR(20) NOT NULL,
  `email_address` VARCHAR(100) NOT NULL,
  `date_of_birth` DATE NOT NULL,
  PRIMARY KEY (`customer_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Plan`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Plan` (
  `plan_id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `plan_type` VARCHAR(50) NOT NULL,
  `plan_name` VARCHAR(100) NOT NULL,
  `plan_duration` INT UNSIGNED NOT NULL DEFAULT (store in months maybe),
  `plan_cost` DECIMAL(10,2) UNSIGNED NOT NULL,
  `plan_features` TEXT NULL DEFAULT '(just an optional description)',
  PRIMARY KEY (`plan_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Transaction`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Transaction` (
  `transaction_id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `transaction_type` VARCHAR(50) NOT NULL,
  `transaction_date` DATE NOT NULL,
  `transaction_amount` DECIMAL(10,2) UNSIGNED NOT NULL,
  `customer_id` INT UNSIGNED NOT NULL,
  `plan_id` INT UNSIGNED NULL,
  PRIMARY KEY (`transaction_id`),
  INDEX `customer_id_idx` (`customer_id` ASC) VISIBLE,
  INDEX `plan_id_idx` (`plan_id` ASC) VISIBLE,
  CONSTRAINT `fk_transaction_customer`
    FOREIGN KEY (`customer_id`)
    REFERENCES `mydb`.`Customer` (`customer_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_transaction_plan_id`
    FOREIGN KEY (`plan_id`)
    REFERENCES `mydb`.`Plan` (`plan_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Call_Traffic`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Call_Traffic` (
  `call_id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `call_date` DATETIME NOT NULL,
  `call_duration` INT UNSIGNED NOT NULL,
  `call_type` VARCHAR(50) NULL,
  `call_cost` DECIMAL(10,2) UNSIGNED NOT NULL,
  `customer_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`call_id`),
  INDEX `customer_id_idx` (`customer_id` ASC) VISIBLE,
  CONSTRAINT `fk_call_traffic_customer_id`
    FOREIGN KEY (`customer_id`)
    REFERENCES `mydb`.`Customer` (`customer_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Customer_Plan`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Customer_Plan` (
  `customer_id` INT UNSIGNED NOT NULL,
  `plan_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`customer_id`, `plan_id`),
  INDEX `plan_id_idx` (`plan_id` ASC) VISIBLE,
  CONSTRAINT `fk_customer_plan_customer_id`
    FOREIGN KEY (`customer_id`)
    REFERENCES `mydb`.`Customer` (`customer_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_customer_plan_plan_id`
    FOREIGN KEY (`plan_id`)
    REFERENCES `mydb`.`Plan` (`plan_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Cancellation`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Cancellation` (
  `cancellation_id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `cancellation_date` DATE NOT NULL,
  `customer_id` INT UNSIGNED NOT NULL,
  `cancellation_reason` TEXT NULL,
  PRIMARY KEY (`cancellation_id`),
  INDEX `customer_id_idx` (`customer_id` ASC) VISIBLE,
  CONSTRAINT `fk_cancellation_customer`
    FOREIGN KEY (`customer_id`)
    REFERENCES `mydb`.`Customer` (`customer_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

USE `mydb` ;

-- -----------------------------------------------------
-- Placeholder table for view `mydb`.`view1`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`view1` (`id` INT);

-- -----------------------------------------------------
-- View `mydb`.`view1`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`view1`;
USE `mydb`;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
